start-at-login = true

# ----------------------------
# Keybindings
# ----------------------------
[mode.main.binding]

# workspaces
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"

alt-u = "workspace prev"
alt-i = "workspace next"

# focus (hjkl)
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"

# move window (shift+hjkl)
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"

# ----------------------------
# Auto-move apps to workspaces
# ----------------------------
[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "com.todesktop.230313mzl4w4u92" # Cursor
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "com.google.Chrome"
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = "com.openai.chat"
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = "com.tinyspeck.slackmacgap"
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = "com.electron.aqua-voice"
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = "md.obsidian"
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = "notion.id"
run = "move-node-to-workspace 4"

# ----------------------------
# Always floating apps
# ----------------------------

[[on-window-detected]]
if.app-id = "com.apple.finder"
run = "layout floating"

[[on-window-detected]]
if.app-id = "jp.kiok.nani"
run = "layout floating"
